from controller import main

try:
    main()
except:
    print('Приложение завершило работу с ошибкой')
